# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  projectPath: '$(Build.SourcesDirectory)/WebApp11May/WebApp11May.csproj'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- task: FileTransform@2
  inputs:
    folderPath: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    enableXmlTransform: false
    enableJsonTransform: true
    jsonTargetFiles: '**/appsettings.json'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure Subscription(4cc400bc-8706-4682-b513-3a847ab32c7f)'
    appType: 'webApp'
    appName: 'webapp11may'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Azure Subscription(4cc400bc-8706-4682-b513-3a847ab32c7f)'
    AuthenticationType: 'server'
    ServerName: 'tcp:webapp11mayserver.database.windows.net,1433'
    DatabaseName: 'webapp11maydb'
    SqlUsername: 'scholaradmin'
    SqlPassword: 'Scholar@12345678'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.ArtifactStagingDirectory)/drop/DemoDBProject.dacpac'
    IpDetectionMethod: 'AutoDetect'