// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DAL.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DAL
{
    public partial interface IAppDbContextProcedures
    {
        Task<List<Usp_GetEmployeeResult>> Usp_GetEmployeeAsync(int? employeeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
